export const questions = [
  // =====================================================================
  // Kapitel 1 · Einführung in die Behavioral Finance
  // =====================================================================
  {
    id: 'bf-k1-q1',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Wie lässt sich Behavioral Finance nach Daxhammer/Facsar definieren?',
    options: [
      'Als rein mathematische Optimierungstheorie für Portfolios ohne psychologische Annahmen',
      'Als verhaltenswissenschaftlich fundierte Finanzmarkttheorie, die von begrenzt rationalen Marktteilnehmern (Homo Oeconomicus Humanus) ausgeht',
      'Als normative Lehre, wie sich ein vollständig rationaler Anleger verhalten muss',
      'Als Teilgebiet der reinen Psychologie ohne ökonomischen Bezug',
    ],
    correctAnswer: 1,
    explanation: 'Behavioral Finance ist eine verhaltenswissenschaftlich fundierte Finanzmarkttheorie. Sie basiert auf der Erkenntnis, dass Marktteilnehmer nur zu begrenzt rationalem Verhalten in der Lage sind; es kristallisiert sich ein Homo Oeconomicus Humanus heraus, der durch kognitive und emotionale Aspekte beeinflusst wird.',
  },
  {
    id: 'bf-k1-q2',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Was kennzeichnet das Maximalprinzip als Ausprägung des ökonomischen Prinzips?',
    options: [
      'Der Input ist fix und der Output wird maximiert',
      'Der Output ist fix und der Input wird minimiert',
      'Sowohl Input als auch Output werden maximiert',
      'Sowohl Input als auch Output sind fix vorgegeben',
    ],
    correctAnswer: 0,
    explanation: 'Maximalprinzip = Input fix, Output maximal (mit gegebenem Mitteleinsatz den größtmöglichen Ertrag erzielen). Das Minimalprinzip dagegen fixiert den Output und minimiert den Input.',
  },
  {
    id: 'bf-k1-q3',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche Annahmen gehören zum Menschenbild des Homo Oeconomicus der Neoklassik?',
    options: [
      'Er hat feststehende Präferenzen',
      'Er ist risikoavers',
      'Er verfügt über vollständige Informationen',
      'Er greift systematisch auf Heuristiken zurück',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Der Homo Oeconomicus handelt nach eigenen Interessen, ist rational (ökonomisches Prinzip), reagiert auf Umweltbedingungen, hat feststehende Präferenzen, ist risikoavers und vollständig informiert. Der Rückgriff auf Heuristiken ist gerade ein Merkmal der begrenzten Rationalität der Verhaltensökonomik, nicht des Homo Oeconomicus.',
  },
  {
    id: 'bf-k1-q4',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Wie unterscheiden sich Ökonomie und Psychologie hinsichtlich ihrer Grundausrichtung?',
    options: [
      'Beide Disziplinen sind rein deskriptiv',
      'Ökonomie ist deskriptiv, Psychologie ist normativ',
      'Ökonomie ist normativ (wie man sich verhalten soll), Psychologie ist deskriptiv (wie der Mensch tatsächlich handelt)',
      'Beide Disziplinen sind rein normativ',
    ],
    correctAnswer: 2,
    explanation: 'Die Ökonomie ist eine normative Disziplin (sie gibt vor, wie sich Wirtschaftssubjekte verhalten müssen, damit optimale Allokationen entstehen). Die Psychologie ist deskriptiv angelegt (sie erklärt Erleben und Verhalten des Menschen).',
  },
  {
    id: 'bf-k1-q5',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche realistischeren Annahmen setzt die Verhaltensökonomik an die Stelle der Kernannahmen des Homo Oeconomicus?',
    options: [
      'Begrenzte Rationalität',
      'Begrenzte Willenskraft',
      'Begrenzter Eigennutz (z. B. Fairness)',
      'Unbegrenzte Informationsverarbeitung',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die Verhaltensökonomik ersetzt die drei Kernannahmen durch begrenzte Rationalität (Fehler bei der Informationsverarbeitung, Rückgriff auf Heuristiken), begrenzte Willenskraft (Vertagung unbequemer Entscheidungen) und begrenzten Eigennutz (Fairness spielt eine Rolle).',
  },
  {
    id: 'bf-k1-q6',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Welcher Zusatzschritt schiebt sich nach der Verhaltensökonomik zwischen objektives Risiko und Entscheidung, der in der Neoklassik fehlt?',
    options: [
      'Die mathematische Erwartungswertbildung',
      'Die subjektive Risikowahrnehmung (geprägt durch Risikodarstellung und Risikoeinstellung)',
      'Die vollständige Arbitrage durch professionelle Investoren',
      'Die Maximierung des Erwartungsnutzens',
    ],
    correctAnswer: 1,
    explanation: 'In der Neoklassik führt objektives Risiko direkt über rationale Entscheider zur Entscheidung. In der Verhaltensökonomik schiebt sich die subjektive Risikowahrnehmung dazwischen, die durch Risikodarstellung (Framing) und individuelle Risikoeinstellung geprägt ist und die Entscheidung verzerrt.',
  },

  // =====================================================================
  // Kapitel 2 · Das Modell der zwei Systeme
  // =====================================================================
  {
    id: 'bf-k2-q1',
    topicId: 'modell-der-zwei-systeme',
    type: 'single',
    question: 'Welche Zuordnung der beiden Denksysteme nach Kahneman ist korrekt?',
    options: [
      'System 1 = langsames Denken (bewusst), System 2 = schnelles Denken (automatisch)',
      'System 1 = schnelles Denken (automatisch, unbewusst), System 2 = langsames Denken (bewusst, konzentriert)',
      'Beide Systeme arbeiten ausschließlich bewusst',
      'System 1 wird nur vom Homo Oeconomicus genutzt',
    ],
    correctAnswer: 1,
    explanation: 'System 1 funktioniert automatisch, schnell und unbewusst ("schnelles Denken"). System 2 ist das bewusste, konzentrierte (aber faule) System für aufwendige Denkprozesse ("langsames Denken").',
  },
  {
    id: 'bf-k2-q2',
    topicId: 'modell-der-zwei-systeme',
    type: 'single',
    question: 'Mit welchem System würde der idealtypische Homo Oeconomicus ausschließlich arbeiten?',
    options: [
      'Ausschließlich mit System 1',
      'Ausschließlich mit System 2',
      'Mit keinem der beiden Systeme',
      'Abwechselnd je nach Tageszeit',
    ],
    correctAnswer: 1,
    explanation: 'Der rationale Homo Oeconomicus wäre ein reiner System-2-Akteur, der jede Entscheidung vollständig rational durchdenkt. Reale Menschen verlassen sich dagegen überwiegend auf das automatische, fehleranfällige System 1.',
  },
  {
    id: 'bf-k2-q3',
    topicId: 'modell-der-zwei-systeme',
    type: 'single',
    question: 'Im Cognitive Reflection Test sank die Fehlerquote durch eine kaum lesbare (disfluente) Schrift. Welche Werte und welche Begründung nennt das Skript?',
    options: [
      'Von 35 % auf 90 %, weil die schlechte Lesbarkeit System 1 zusätzlich verwirrt',
      'Von 90 % auf 35 %, weil die kognitive Beanspruchung System 2 mobilisiert und die intuitive Antwort von System 1 verwirft',
      'Von 50 % auf 10 %, weil die Probanden die Aufgabe übersprungen haben',
      'Sie blieb unverändert, da die Lesbarkeit keinen Einfluss hat',
    ],
    correctAnswer: 1,
    explanation: 'Eine starke kognitive Beanspruchung mobilisiert unabhängig von ihrer Ursache System 2, das die von System 1 vorgeschlagene intuitive Antwort verwirft. Daher senkte die erschwerte Lesbarkeit die Fehlerquote von 90 % auf 35 % (Frederick 2005).',
  },
  {
    id: 'bf-k2-q4',
    topicId: 'modell-der-zwei-systeme',
    type: 'multiple',
    question: 'Welche Auslöser (Ursachen) der kognitiven Leichtigkeit nennt das Schaubild nach Kahneman?',
    options: [
      'Wiederholte Erfahrung',
      'Klare Darstellung',
      'Geprimte Vorstellung',
      'Gute Laune',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'Die vier Auslöser kognitiver Leichtigkeit sind wiederholte Erfahrung, klare Darstellung, geprimte Vorstellung und gute Laune. Ihre Wirkungen: Etwas fühlt sich vertraut an, erscheint wahr, fühlt sich gut an und erscheint mühelos.',
  },
  {
    id: 'bf-k2-q5',
    topicId: 'modell-der-zwei-systeme',
    type: 'single',
    question: 'Worin besteht der Konflikt bei der Stroop-artigen Aufgabe?',
    options: [
      'Zwischen Sehen und Hören',
      'Zwischen dem automatischen Lesen (System 1) und der bewussten Aufgabe (System 2), z. B. Position oder Schreibweise zu benennen',
      'Zwischen Kurzzeit- und Langzeitgedächtnis',
      'Zwischen zwei gleich starken Wahrnehmungshypothesen',
    ],
    correctAnswer: 1,
    explanation: 'Die Wortbedeutung (z. B. "rechts", "groß") widerspricht der zu nennenden Eigenschaft (Position bzw. Schreibweise). Das automatische Lesen von System 1 kollidiert mit der kontrollierten Aufgabe von System 2; das Unterdrücken der automatischen Reaktion kostet Anstrengung und verlangsamt.',
  },
  {
    id: 'bf-k2-q6',
    topicId: 'modell-der-zwei-systeme',
    type: 'single',
    question: 'Warum sind intuitive Denkfehler laut der zentralen Schlussfolgerung schwer zu verhindern?',
    options: [
      'Weil System 2 grundsätzlich nicht aktiviert werden kann',
      'Weil System 1 nicht abgestellt werden kann und automatisch reagiert',
      'Weil Menschen über kein bewusstes Denken verfügen',
      'Weil Heuristiken stets zu richtigen Ergebnissen führen',
    ],
    correctAnswer: 1,
    explanation: 'Intuitive Denkfehler sind schwer zu verhindern, da System 1 nicht abgestellt werden kann und automatisch reagiert. System 2 kann eine intuitive Antwort nur korrigieren, wenn es überhaupt aktiv wird.',
  },

  // =====================================================================
  // Kapitel 3 · Heuristiken und kognitive Verzerrungen
  // =====================================================================
  {
    id: 'bf-k3-q1',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Wie grenzt das Skript Heuristik und Algorithmus voneinander ab?',
    options: [
      'Eine Heuristik liefert in gleichen Situationen immer dasselbe Ergebnis, ein Algorithmus ist eine Faustregel',
      'Eine Heuristik ist eine schnelle "gut-genug"-Regel bei eingeschränktem Wissen (System 1), ein Algorithmus ein normatives, reproduzierbares Verfahren (System 2)',
      'Beide sind identisch und unterscheiden sich nur im Namen',
      'Ein Algorithmus ist systematisch verzerrt, eine Heuristik dagegen normativ richtig',
    ],
    correctAnswer: 1,
    explanation: 'Die Heuristik ist eine Daumen-/Faustregel zur kognitiven Entlastung bei eingeschränktem Wissen und wenig Zeit, sie ist aber systematisch verzerrt (Biases). Der Algorithmus liefert in gleichen Situationen gleiche, reproduzierbare und prüfbare Ergebnisse und ist der normative Maßstab.',
  },
  {
    id: 'bf-k3-q2',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Was beschreibt die Verfügbarkeitsheuristik?',
    options: [
      'Wahrscheinlichkeiten werden danach geschätzt, wie leicht entsprechende Erinnerungen abrufbar sind',
      'Wahrscheinlichkeiten werden exakt mit dem Bayes-Theorem berechnet',
      'Ereignisse werden überbewertet, weil sie in ein Schema passen',
      'Der erste genannte Zahlenwert verzerrt die Schätzung',
    ],
    correctAnswer: 0,
    explanation: 'Die Verfügbarkeitsheuristik beurteilt Wahrscheinlichkeiten nach der Zugänglichkeit relevanter Erinnerungen: Szenarien, die auf leicht abrufbaren Erinnerungen basieren, werden als wahrscheinlicher erachtet. Dadurch werden mediengetriebene, dramatische Risiken über-, stille Risiken (Krankheiten) unterschätzt.',
  },
  {
    id: 'bf-k3-q3',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Im Brustkrebs-Beispiel (Dawes 1988) stammten 93 % der Fälle aus einer Hochrisikogruppe. Wie hoch ist das tatsächliche Erkrankungsrisiko innerhalb dieser Gruppe nach dem Satz von Bayes?',
    options: [
      '93 %',
      '57 %',
      '12,2 %',
      '7,5 %',
    ],
    correctAnswer: 2,
    explanation: 'Mit p(Bk)=0,075, p(Hr|Bk)=0,93 und p(Hr)=0,57 ergibt der Satz von Bayes p(Bk|Hr) = (0,075·0,93)/0,57 = 12,2 %. Die 93 % sind p(Hochrisikogruppe | Brustkrebs), nicht das Erkrankungsrisiko der Gruppe; p(A|B) und p(B|A) dürfen nicht verwechselt werden.',
  },
  {
    id: 'bf-k3-q4',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Wie wählt die Mehrheit im Asian-Disease-Problem je nach Frame bei identischem Erwartungswert?',
    options: [
      'Im Gewinn-Frame risikofreudig, im Verlust-Frame risikoavers',
      'Im Gewinn-Frame risikoavers (sichere Rettung), im Verlust-Frame risikofreudig',
      'In beiden Frames stets die riskante Alternative',
      'In beiden Frames stets die sichere Alternative',
    ],
    correctAnswer: 1,
    explanation: 'Obwohl A/C und B/D rechnerisch denselben Erwartungswert haben, entscheiden Menschen im Gewinn-Frame (Rettung) risikoavers und wählen die sichere Therapie A, im Verlust-Frame (Sterben) dagegen risikofreudig und wählen Therapie D.',
  },
  {
    id: 'bf-k3-q5',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'multiple',
    question: 'Welche Aussagen zu Overconfidence und ihren Folgen sind korrekt?',
    options: [
      'Nach Svenson (1981) halten sich 93 % der US-Autofahrer für besser als der Durchschnitt',
      'Overconfidence führt über die "Difference in Opinion" zu exzessivem Handel',
      'Höhere Handelsaktivität (Portfolioumsatz) geht im Querschnitt mit niedrigerer Nettorendite einher (Barber/Odean 2000)',
      'Mit steigender Aufgabenschwierigkeit sinkt der Überoptimismus (Hard-is-easy-Effekt)',
    ],
    correctAnswers: [0, 1, 2],
    explanation: '93 % der US-Autofahrer halten sich für überdurchschnittlich (Svenson 1981); die "Difference in Opinion" treibt exzessiven Handel; höhere Handelsaktivität senkt die Nettorendite (Barber/Odean 2000). Der Hard-is-easy-Effekt besagt jedoch: Mit steigender Aufgabenschwierigkeit STEIGT der Überoptimismus.',
  },
  {
    id: 'bf-k3-q6',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Im Kinobeispiel zum Mental Accounting verzichten 54 % nach einer verlorenen Karte, aber nur 12 % nach einem verlorenen Geldschein auf den Neukauf. Was zeigt das?',
    options: [
      'Dass der ökonomische Verlust in beiden Fällen unterschiedlich hoch ist',
      'Dass Menschen Geld getrennten mentalen Konten zuordnen, obwohl der Verlust identisch ist',
      'Dass die Verfügbarkeitsheuristik die Entscheidung steuert',
      'Dass die Regression zur Mitte wirkt',
    ],
    correctAnswer: 1,
    explanation: 'Obwohl in beiden Fällen ökonomisch 10 € verloren sind, verzichten bei der verlorenen Karte (Konto "Kino") 54 % auf den Neukauf, bei verlorenem Bargeld (Konto "Bargeld") nur 12 %. Die mentale Kontenzuordnung steuert das Verhalten (Thaler 1999).',
  },
  {
    id: 'bf-k3-q7',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Wie wird der Ankerungsindex im Mammutbaum-Beispiel berechnet und interpretiert?',
    options: [
      'Differenz Anker / Differenz Schätzung; 100 % bedeutet, der Anker ist irrelevant',
      '(257−86)/(366−55) = 55 %; 100 % = Menschen folgen sklavisch dem Anker, 0 % = der Anker spielt keine Rolle',
      'Differenz Schätzung minus Differenz Anker; ein Wert von 55 € misst die Verzerrung',
      'Schätzung geteilt durch Marktwert; 55 % bedeutet eine faire Schätzung',
    ],
    correctAnswer: 1,
    explanation: 'Der Ankerungsindex = Differenz der Schätzungen / Differenz der Anker = (257−86)/(366−55) = 171/311 = 55 %. 100 % bedeutet, dass Menschen sklavisch den Anker wählen, 0 % bedeutet, dass der Anker keine Rolle spielt.',
  },
  {
    id: 'bf-k3-q8',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Worin unterscheiden sich Decoy-Effekt und Phantom-Lockvogel-Effekt?',
    options: [
      'Beim Decoy existiert der minderwertige Köder real (wird nur kaum gewählt), beim Phantom-Effekt ist das attraktive Angebot gar nicht verfügbar',
      'Beim Decoy ist das Angebot nicht lieferbar, beim Phantom-Effekt existiert es real',
      'Beide bezeichnen exakt denselben Mechanismus',
      'Der Decoy-Effekt betrifft nur Aktien, der Phantom-Effekt nur Konsumgüter',
    ],
    correctAnswer: 0,
    explanation: 'Beim Decoy-Effekt (asymmetrische Dominanz) wird ein minderwertiger Köder real angeboten, aber kaum gewählt (Economist: Print-only steigert die Wahl von Print+Online von 32 % auf 84 %). Beim Phantom-Lockvogel-Effekt ist das attraktive Angebot "gerade nicht lieferbar", existiert also gar nicht.',
  },

  // =====================================================================
  // Kapitel 4 · Entscheidungen unter Unsicherheit
  // =====================================================================
  {
    id: 'bf-k4-q1',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Wodurch unterscheiden sich Ungewissheit und Risiko i.e.S.?',
    options: [
      'Bei Ungewissheit sind die Eintrittswahrscheinlichkeiten bekannt, bei Risiko i.e.S. nicht',
      'Bei Ungewissheit sind nur die möglichen Zustände bekannt; bei Risiko i.e.S. zusätzlich deren Eintrittswahrscheinlichkeiten',
      'Bei Ungewissheit ist der eintretende Zustand sicher bekannt',
      'Beide Begriffe sind synonym',
    ],
    correctAnswer: 1,
    explanation: 'Bei Ungewissheit kennt man nur die möglichen Umweltzustände, nicht aber deren Eintrittswahrscheinlichkeiten (Einsatz von Heuristiken). Bei Risiko i.e.S. sind die Zustände UND ihre (objektiven oder subjektiven) Eintrittswahrscheinlichkeiten bekannt (stochastische Modelle).',
  },
  {
    id: 'bf-k4-q2',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Welche Alternative empfiehlt die Maximin-Regel (Wald-Regel) auf der Beispielmatrix?',
    options: [
      'a₂, weil sie das höchste Zeilenmaximum (21) hat',
      'a₅, weil sie das höchste Zeilenminimum (6) hat',
      'a₁, weil sie den geringsten maximalen Schaden hat',
      'a₃, weil sie den höchsten Erwartungswert hat',
    ],
    correctAnswer: 1,
    explanation: 'Die Maximin-Regel bewertet jede Zeile mit ihrem schlechtesten Ergebnis (extrem pessimistisch) und wählt das höchste Zeilenminimum. Im Beispiel sind die Zeilenminima 5/1/5/3/6/2, höchstes Minimum ist a₅ (6).',
  },
  {
    id: 'bf-k4-q3',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Welche zentrale Kritik gilt für die Bayes-Regel (μ-Prinzip)?',
    options: [
      'Sie ist nicht berechenbar, weil keine Wahrscheinlichkeiten vorliegen',
      'Sie berücksichtigt die Streuung der Ergebnisse nicht und passt daher nur für risikoneutrale Entscheider',
      'Sie überbewertet systematisch die Standardabweichung',
      'Sie ist nur für risikofreudige Entscheider geeignet',
    ],
    correctAnswer: 1,
    explanation: 'Die Bayes-Regel wählt die Alternative mit dem höchsten Erwartungswert μ = Σ z_ij·p_j. Sie ist einfach und liefert bei häufigen Entscheidungen gute Ergebnisse, berücksichtigt aber die Streuung (das Risiko) nicht und passt daher nur für risikoneutrale Entscheider.',
  },
  {
    id: 'bf-k4-q4',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Im Lotterie-Beispiel (50 % → 100 €, 50 % → 0 €) ist der Entscheider bei s = 40 € indifferent. Wie hoch ist die Risikoprämie und welche Risikoeinstellung folgt daraus?',
    options: [
      'π = 0, risikoneutral',
      'π = 10, risikoscheu',
      'π = −10, risikofreudig',
      'π = 50, risikoscheu',
    ],
    correctAnswer: 1,
    explanation: 'Der Erwartungswert beträgt 0,5·100 + 0,5·0 = 50. Die Risikoprämie π = E(X) − s = 50 − 40 = 10. Da π > 0, verhält sich der Entscheider risikoscheu.',
  },
  {
    id: 'bf-k4-q5',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Welche Krümmung der Nutzenfunktion entspricht risikofreudigem Verhalten?',
    options: [
      'Konkav (Risikoprämie π > 0)',
      'Linear (Risikoprämie π = 0)',
      'Konvex (Risikoprämie π < 0)',
      'Konkav (Risikoprämie π < 0)',
    ],
    correctAnswer: 2,
    explanation: 'Die Krümmung der Nutzenfunktion bestimmt die Risikoeinstellung: konkav = risikoavers (Erwartungswert > Sicherheitsäquivalent, π > 0), linear = risikoneutral (π = 0), konvex = risikofreudig (Erwartungswert < Sicherheitsäquivalent, π < 0).',
  },
  {
    id: 'bf-k4-q6',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Im Bernoulli-Beispiel haben sichere (a₁) und spekulative (a₂) Anlage denselben Erwartungswert von 110.000 €, aber bei u(z)=ln(z) ergibt sich E[u(a₁)] = 4,70 und E[u(a₂)] = 4,66. Was folgt daraus?',
    options: [
      'a₂ wird gewählt, da die spekulative Anlage den höheren Erwartungswert hat',
      'a₁ wird gewählt (a₁ ≻ a₂), da die konkave Nutzenfunktion der sicheren Anlage den höheren Erwartungsnutzen verleiht (Risikoaversion)',
      'Beide Anlagen sind gleichwertig, da der Erwartungswert identisch ist',
      'a₂ wird gewählt, weil bei gleichem Erwartungswert stets das höhere Risiko bevorzugt wird',
    ],
    correctAnswer: 1,
    explanation: 'Trotz gleichem Erwartungswert liefert wegen der konkaven Nutzenfunktion (ln) die sichere Anlage den höheren Erwartungsnutzen (4,70 vs. 4,66). Nach dem Bernoulli-Prinzip gilt a₁ ≻ a₂: Die sichere Anlage wird gewählt (Risikoaversion).',
  },

  // =====================================================================
  // Kapitel 5 · Zeit in der Ökonomie
  // =====================================================================
  {
    id: 'bf-k5-q1',
    topicId: 'zeit-in-der-oekonomie',
    type: 'multiple',
    question: 'Welche der folgenden Gründe nennt Beck (2014) für die Existenz eines Zinssatzes?',
    options: [
      'Unsicherheit und Kompensation für Risiko',
      'Opportunitätskosten und Inflation',
      'Ungeduld und "multiple Persönlichkeiten" (heutiges Ich vs. späteres Selbst)',
      'Vollständige Informationseffizienz der Märkte',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die sechs Gründe für die Existenz eines Zinssatzes sind: Unsicherheit, Risikokompensation, Opportunitätskosten, Inflation, Ungeduld und multiple Persönlichkeiten. Informationseffizienz gehört nicht dazu.',
  },
  {
    id: 'bf-k5-q2',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Wodurch unterscheidet sich das hyperbolische Diskontieren formal vom exponentiellen Diskontieren des DU-Modells?',
    options: [
      'Beim hyperbolischen Diskontieren steht (1+i)^n im Nenner, beim exponentiellen (1+i·n)',
      'Beim hyperbolischen Diskontieren steht (1+i·n) im Nenner, beim exponentiellen (1+i)^n',
      'Beide nutzen denselben Diskontfaktor, unterscheiden sich nur im Vorzeichen',
      'Das hyperbolische Diskontieren verzichtet ganz auf einen Diskontfaktor',
    ],
    correctAnswer: 1,
    explanation: 'Im DU-Modell (exponentiell) steht (1+i)^n im Nenner, beim hyperbolischen Diskontieren dagegen (1+i·n). Nur Letzteres erzeugt eine Präferenzumkehr, weil die Gegenwartspräferenz steigt, je näher das Ereignis rückt.',
  },
  {
    id: 'bf-k5-q3',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Was zeigen die Befunde von Thaler (1981) zu den implizit geforderten Jahreszinsen (ca. 400 % bei 1 Monat, 233 % bei 1 Jahr, 21 % bei 10 Jahren)?',
    options: [
      'Dass der geforderte implizite Jahreszins mit zunehmender Wartezeit konstant bleibt',
      'Dass der geforderte implizite Jahreszins mit zunehmender Wartezeit sinkt – ein empirischer Beleg für hyperbolisches Diskontieren',
      'Dass Menschen für lange Fristen höhere Zinsen verlangen als für kurze',
      'Dass das DU-Modell empirisch perfekt bestätigt wird',
    ],
    correctAnswer: 1,
    explanation: 'Mit zunehmender Wartezeit sinkt der geforderte implizite Jahreszins (ca. 400 % → 233 % → 21 %). Das ist ein empirischer Beleg für hyperbolisches Diskontieren und widerspricht dem konstanten Diskontsatz des DU-Modells.',
  },
  {
    id: 'bf-k5-q4',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Was besagt die Zeitinkonsistenz?',
    options: [
      'Eine Entscheidung sollte sich nicht ändern, wenn man beide Optionen um dieselbe Zeitspanne verschiebt; tut sie es doch, liegt Zeitinkonsistenz vor',
      'Künftige Zahlungen werden grundsätzlich nicht diskontiert',
      'Der Diskontfaktor ist bei allen Menschen identisch',
      'Gewinne und Verluste werden stets gleich diskontiert',
    ],
    correctAnswer: 0,
    explanation: 'Eine Entscheidung zwischen zwei Optionen sollte sich nicht ändern, wenn man beide um die gleiche Zeitspanne verschiebt. Tut sie es doch, liegt Zeitinkonsistenz vor – eine Verletzung der intertemporalen Nutzenmaximierung und des DU-Ansatzes (u. a. durch Selbstkontrollprobleme).',
  },
  {
    id: 'bf-k5-q5',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Was besagt der Vorzeicheneffekt als weitere Zeitanomalie?',
    options: [
      'Verluste werden stärker diskontiert als Gewinne',
      'Gewinne werden stärker diskontiert als Verluste (Gewinne lieber sofort vereinnahmen, Verluste aufschieben)',
      'Große Beträge werden stärker diskontiert als kleine',
      'Es gibt keinen Unterschied in der Diskontierung von Gewinnen und Verlusten',
    ],
    correctAnswer: 1,
    explanation: 'Der Vorzeicheneffekt besagt, dass Menschen Gewinne stärker diskontieren als Verluste, Gewinne also mit höherem Zinssatz abgezinst werden. Verhaltenslogik: Gewinne lieber sofort vereinnahmen, Verluste lieber aufschieben (Thaler 1981).',
  },
  {
    id: 'bf-k5-q6',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Welche Lohnprofile bevorzugen Probanden trotz gleicher Gesamtsumme?',
    options: [
      'Das fallende Profil (100, 90, 80)',
      'Das steigende Profil (80, 90, 100)',
      'Beide gleichermaßen, da die Summe identisch ist',
      'Ein konstantes Profil',
    ],
    correctAnswer: 1,
    explanation: 'Trotz gleicher Gesamtsumme (270) bevorzugen Probanden das steigende Profil (80, 90, 100) – ein Widerspruch zur reinen DU-Logik. Gründe sind u. a. Verlustaversion (sinkender Lohn als Verlust erlebt), Gewöhnung und Antizipationsnutzen.',
  },

  // =====================================================================
  // Kapitel 6 · Prospect Theory und ihre Konsequenzen
  // =====================================================================
  {
    id: 'bf-k6-q1',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Im Allais-Paradoxon (Problem I) ist E(A) = 2.409 € und E(B) = 2.400 €. Welche Alternative wäre rational, und welche wählen viele Menschen tatsächlich?',
    options: [
      'Rational und tatsächlich gewählt: A',
      'Rational wäre A, tatsächlich gewählt wird aber B',
      'Rational wäre B, tatsächlich gewählt wird A',
      'Beide Alternativen sind gleichwertig',
    ],
    correctAnswer: 1,
    explanation: 'Da E(A) = 2.409 € > E(B) = 2.400 €, wäre A rational (höherer Erwartungswert). Tatsächlich präferieren viele Menschen aber die sichere Alternative B. In Problem II wählen sie C – die abgeleiteten Ungleichungen widersprechen sich (Anomalie), was die Prospect Theory motiviert.',
  },
  {
    id: 'bf-k6-q2',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Wie ist die Prospect Theory (Kahneman/Tversky 1979) im Verhältnis zur Erwartungsnutzentheorie einzuordnen?',
    options: [
      'Sie ist normativ und beschreibt optimale Entscheidungen in einer Phase',
      'Sie ist deskriptiv, modelliert zwei Phasen und erklärt Entscheidungen, die der EU-Theorie widersprechen',
      'Sie ist identisch zur Erwartungsnutzentheorie',
      'Sie ist eine rein mathematische Variante des CAPM',
    ],
    correctAnswer: 1,
    explanation: 'Die Prospect Theory ist ein deskriptives Modell (reale statt optimaler Entscheidungen). Sie umfasst zwei Phasen (Editing und Evaluation), berücksichtigt Wahrnehmungsverzerrungen (Biases) und erklärt Entscheidungen, die der normativen EU-Theorie widersprechen.',
  },
  {
    id: 'bf-k6-q3',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'multiple',
    question: 'Welche der folgenden gehören zu den Editing-Operationen der ersten Phase der Prospect Theory?',
    options: [
      'Vereinfachung (z. B. Auf- oder Abrunden)',
      'Kombination (Addition der Wahrscheinlichkeiten identischer Ergebnisse)',
      'Segregation (Trennung sicherer und unsicherer Konsequenzen)',
      'Maximierung des CAPM-Beta',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Zu den Editing-Operationen gehören Vereinfachung, Kombination, Segregation, Kodierung (Festlegung eines Referenzpunkts) und Cancellation (Streichung sehr unwahrscheinlicher oder identischer Bestandteile). Die Maximierung eines CAPM-Beta gehört nicht dazu.',
  },
  {
    id: 'bf-k6-q4',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'multiple',
    question: 'Welche Eigenschaften kennzeichnen die S-förmige Wertfunktion der Prospect Theory?',
    options: [
      'Im Gewinnbereich konkav (risikoscheu)',
      'Im Verlustbereich konvex (risikofreudig)',
      'Im Verlustbereich steiler als im Gewinnbereich (Verlustaversion, ca. Faktor 2)',
      'Sie bewertet absolute Vermögensniveaus statt relativer Veränderungen',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die Wertfunktion ist im Gewinnbereich konkav (risikoscheu), im Verlustbereich konvex (risikofreudig) und für Verluste steiler (Verlustaversion, Verluste ca. doppelt so stark bewertet). Bewertet werden relative Veränderungen gegenüber einem Referenzpunkt, nicht absolute Vermögensniveaus.',
  },
  {
    id: 'bf-k6-q5',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Was besagt der Reflexionseffekt?',
    options: [
      'Bei positiven Prospekten dominiert Risikofreude, bei negativen Risikoaversion',
      'Bei positiven Prospekten dominiert Risikoaversion, bei negativen Prospekten Risikofreude – die Spiegelung kehrt das Risikoverhalten um',
      'Gewinne und Verluste werden völlig symmetrisch bewertet',
      'Die Risikoeinstellung ist unabhängig vom Vorzeichen des Prospekts',
    ],
    correctAnswer: 1,
    explanation: 'Der Reflexionseffekt: Die Spiegelung von Gewinnen zu Verlusten kehrt das Risikoverhalten um. Bei positiven Prospekten dominiert Risikoaversion, bei negativen Prospekten Risikofreude (z. B. Fall 1: 80 % wählen B bei positiven, 92 % wählen C bei negativen Prospekten).',
  },
  {
    id: 'bf-k6-q6',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Wie verzerrt die Gewichtungsfunktion π objektive Wahrscheinlichkeiten?',
    options: [
      'Kleine Wahrscheinlichkeiten werden unterbewertet, mittlere/hohe überbewertet',
      'Kleine Wahrscheinlichkeiten werden überbewertet (π(p) > p), mittlere/hohe unterbewertet (π(p) < p)',
      'Alle Wahrscheinlichkeiten werden exakt richtig gewichtet',
      'π ist immer gleich der objektiven Wahrscheinlichkeit p',
    ],
    correctAnswer: 1,
    explanation: 'Die Gewichtungsfunktion überbewertet objektiv kleine Wahrscheinlichkeiten (π(p) > p) und unterbewertet mittlere/hohe (π(p) < p). An den Rändern (0 %/100 %) ist sie sehr steil (Certainty-Effekt). π ist keine Maßzahl der Wahrscheinlichkeit, sondern Ausdruck der subjektiven Einschätzung.',
  },
  {
    id: 'bf-k6-q7',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Was beschreibt der Dispositionseffekt als Konsequenz der Prospect Theory?',
    options: [
      'Anleger realisieren Verluste zu früh und sitzen Gewinne aus',
      'Anleger realisieren Gewinne zu früh und sitzen Verluste aus – jeweils relativ zum Einstandspreis als Bezugspunkt',
      'Anleger handeln stets antizyklisch und kaufen günstig',
      'Anleger ignorieren den Einstandspreis vollständig',
    ],
    correctAnswer: 1,
    explanation: 'Beim Dispositionseffekt realisieren Anleger Gewinne zu früh (Risikoaversion im konkaven Gewinnbereich) und sitzen Verluste aus (Risikofreude im konvexen Verlustbereich) – jeweils relativ zum Einstandspreis als Bezugspunkt.',
  },

  // =====================================================================
  // Kapitel 7 · Altersvorsorge und private Finanzplanung
  // =====================================================================
  {
    id: 'bf-k7-q1',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'multiple',
    question: 'Warum ist die Altersvorsorge besonders anfällig für Verhaltensverzerrungen?',
    options: [
      'Außergewöhnlich langer Anlagehorizont',
      'Begrenzte Lernmöglichkeiten',
      'Oft geringe oder fehlende Kenntnisse über Finanzmärkte',
      'Es handelt sich um eine einmalige, leicht zu korrigierende Entscheidung',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die Altersvorsorge ist besonders anfällig wegen des extrem langen Anlagehorizonts, der begrenzten Lernmöglichkeiten und des oft fehlenden Finanzwissens. Gerade die fehlende Korrekturmöglichkeit über die Zeit macht sie heikel.',
  },
  {
    id: 'bf-k7-q2',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'single',
    question: 'Was zeigt der Vergleich der Organspende-Zustimmungsraten zwischen Opt-In- und Opt-Out-Ländern (Johnson et al. 2003)?',
    options: [
      'Opt-In-Länder erreichen die höchsten Zustimmungsraten (~86-100 %)',
      'Der voreingestellte Default treibt die Zustimmungsrate: Opt-In ~4-28 %, Opt-Out ~86-100 %',
      'Die Zustimmungsrate hängt allein von der wahren Präferenz ab',
      'Opt-In und Opt-Out führen zu identischen Quoten',
    ],
    correctAnswer: 1,
    explanation: 'In Opt-In-Ländern (aktive Zustimmung nötig) liegt die Zustimmung nur bei ~4-28 %, in Opt-Out-Ländern (Widerspruch nötig) bei ~86-100 %. Der voreingestellte Default treibt die Zustimmungsrate, nicht die wahre Präferenz – ein extrem robuster Default-Effekt.',
  },
  {
    id: 'bf-k7-q3',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'single',
    question: 'Was demonstriert das Marmeladen-Experiment (Iyengar/Lepper 2000) zum Choice Overload?',
    options: [
      'Größere Auswahl (24 Sorten) zieht mehr Kunden an (60 % bleiben stehen), führt aber zu deutlich weniger Käufen (nur 3 % vs. 30 %)',
      'Größere Auswahl führt zu mehr Käufen und mehr Stehenbleibenden',
      'Begrenzte Auswahl (6 Sorten) zieht 60 % der Kunden an',
      'Die Auswahlgröße hat keinen Einfluss auf das Kaufverhalten',
    ],
    correctAnswer: 0,
    explanation: 'Bei begrenzter Auswahl (6 Sorten) blieben 40 % stehen, davon kauften ~30 %. Bei umfangreicher Auswahl (24 Sorten) blieben mehr stehen (60 %), aber nur 3 % kauften. Große Auswahl wirkt attraktiver, lähmt aber die Entscheidung – beide Effekte gehören zusammen.',
  },
  {
    id: 'bf-k7-q4',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'single',
    question: 'Was besagt die bedingte 1/N-Heuristik bei der Anlage von Altersvorsorgebeiträgen (UC 34 % vs. TWA 75 % Aktienquote)?',
    options: [
      'Teilnehmer optimieren ihre Aktienquote sorgfältig unabhängig vom Menü',
      'Teilnehmer wählen 3-4 Fonds und verteilen gleichmäßig; die Aktienquote hängt dann allein vom Verhältnis Aktien-/Anleihefonds im Menü ab',
      'Teilnehmer investieren stets vollständig in Aktienfonds',
      'Die Aktienquote ist immer 50 %, unabhängig vom Menü',
    ],
    correctAnswer: 1,
    explanation: 'Teilnehmer wählen 3-4 Fonds und verteilen ihr Geld anschließend gleichmäßig (naive 1/N-Diversifikation). Dadurch hängt die Aktienquote allein vom Verhältnis Aktien-/Anleihefonds im Menü ab: University of California 34 % (4 fest, 1 Aktie), TWA 75 % (1 fest, 5 Aktie) – ein reiner Menüeffekt.',
  },
  {
    id: 'bf-k7-q5',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'multiple',
    question: 'Welche Lösungen gegen Verhaltensverzerrungen in der Altersvorsorge werden im Skript genannt?',
    options: [
      'Automatische Anmeldung (Opt-Out) gegen Trägheit',
      'Automatische Beitragserhöhung (SMarT-Programm) gegen Gegenwartspräferenzen',
      'Automatisches Rebalancing über Lebenszyklusfonds gegen naive Diversifizierung',
      'Vergrößerung des Fondsmenüs zur Förderung der Teilnahme',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Lösungen sind: automatische Anmeldung (Opt-Out) gegen Trägheit, einfache Auswahl gegen Komplexität, automatische Erhöhung (SMarT) und das Greifbarmachen des zukünftigen Selbst gegen Gegenwartspräferenzen sowie automatisches Rebalancing (Lebenszyklusfonds) gegen naive Diversifizierung. Ein größeres Menü verschärft das Problem (Choice Overload), es löst es nicht.',
  },
  {
    id: 'bf-k7-q6',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'single',
    question: 'Was zeigt die Trendfolge (Extrapolation) der Aktienquote bei der Anlage (Benartzi/Thaler 2007)?',
    options: [
      'Die Aktienquote aller Teilnehmer schwankt sehr stark mit dem Markt',
      'Neue Teilnehmer richten ihre Aktienquote stark nach dem Markt aus (Einbruch auf 54 % im Jahr 2002), während die Quote aller (träger) Teilnehmer kaum schwankt',
      'Neue Teilnehmer halten ihre Aktienquote völlig konstant',
      'Die Aktienquote ist unabhängig vom Marktgeschehen',
    ],
    correctAnswer: 1,
    explanation: 'Neue Teilnehmer extrapolieren die jüngste Marktentwicklung: hohe Aktienquoten in der Hausse, dramatischer Einbruch auf 54 % im Jahr 2002 nach dem Markteinbruch. Die Quote aller (träger) Teilnehmer schwankt kaum (~64 %).',
  },

  // =====================================================================
  // Kapitel 8 · Spekulationsblasen an Finanzmärkten
  // =====================================================================
  {
    id: 'bf-k8-q1',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'Wie wird eine Spekulationsblase im Skript definiert?',
    options: [
      'Eine kurzfristige, geringfügige Preisschwankung um den Fundamentalwert',
      'Eine starke und langfristige Übertreibung bei Preisen für Wertpapiere, Immobilien oder andere Anlagegüter',
      'Eine staatlich verordnete Preisbindung',
      'Eine reine Erscheinung effizienter Märkte',
    ],
    correctAnswer: 1,
    explanation: 'Eine Spekulationsblase ist eine starke und langfristige Übertreibung bei Preisen für Wertpapiere, Immobilien oder andere Anlagegüter. Die Preise koppeln sich vom Fundamentalwert ab – ein Zeichen für Anomalien an Finanzmärkten.',
  },
  {
    id: 'bf-k8-q2',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'Welche der vier Kategorien des Herdentriebs beschreibt, dass man sich aus Sorge um den eigenen Ruf der Gruppenmeinung anschließt?',
    options: [
      'Informationskaskaden',
      'Reputationsinteressen',
      'Informationsquellen',
      'Historische Marktbewegungen',
    ],
    correctAnswer: 1,
    explanation: 'Reputationsinteressen meinen, dass man sich aus Sorge um den eigenen Ruf der Gruppenmeinung anschließt und eigene Infos vernachlässigt. Informationskaskaden dagegen meinen das Ignorieren eigener Informationen zugunsten der Masse.',
  },
  {
    id: 'bf-k8-q3',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'In welcher Reihenfolge verlaufen die fünf Phasen des Kindleberger/Minsky-Modells?',
    options: [
      'Euphorie → Verlagerung → Positives Feedback → Abscheu → Kritische Phase',
      'Verlagerung → Positives Feedback → Euphorie → Kritische Phase → Abscheu',
      'Positives Feedback → Verlagerung → Kritische Phase → Euphorie → Abscheu',
      'Verlagerung → Euphorie → Positives Feedback → Abscheu → Kritische Phase',
    ],
    correctAnswer: 1,
    explanation: 'Das Kindleberger/Minsky-Modell beschreibt den Blasenverlauf in fünf Phasen: Verlagerung (exogener Schock) → Positives Feedback (Fremdkapital, Feedback-Loop) → Euphorie (Überschätzung der Renditen) → Kritische Phase (finanzielle Not, Insider verkaufen) → Abscheu (Panik, Crash).',
  },
  {
    id: 'bf-k8-q4',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'Was kennzeichnet eine "rationale" bzw. fast-rationale Spekulationsblase ("Markt der größeren Narren")?',
    options: [
      'Die Marktteilnehmer wissen, dass die Blase platzen wird, kennen aber den Zeitpunkt nicht',
      'Die Preise sind grundsätzlich vom Fundamentalwert entkoppelt und unbeobachtbar',
      'Sie entsteht ausschließlich durch unzureichende Einpreisung von Informationen',
      'Niemand erkennt, dass es sich um eine Blase handelt',
    ],
    correctAnswer: 0,
    explanation: 'Bei rationalen/fast-rationalen Blasen ist der Preis bei rationalen Erwartungen eine Funktion des erwarteten (Wieder-)Verkaufswerts. Die Marktteilnehmer wissen, dass die Blase platzen wird, kennen aber den Zeitpunkt nicht – daher "Markt der größeren Narren".',
  },
  {
    id: 'bf-k8-q5',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'Welche Institution wurde als Reaktion auf den Börsencrash von 1929 gegründet?',
    options: [
      'Die EZB',
      'Die SEC (US-Börsenaufsicht)',
      'Lehman Brothers',
      'Der Internationale Währungsfonds',
    ],
    correctAnswer: 1,
    explanation: 'In der Abscheu-Phase des Crashs von 1929 wurde die SEC gegründet; zudem gingen bis 1933 rund 40 % aller Banken bankrott. Lehman Brothers (2008) gehört dagegen zur Subprime-Krise – beides nicht verwechseln.',
  },
  {
    id: 'bf-k8-q6',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'multiple',
    question: 'Welche volkswirtschaftlichen Effekte von Spekulationsblasen sind korrekt zugeordnet?',
    options: [
      'Positiv: Einkommens- und Vermögenseffekt (steigende Konsummöglichkeiten)',
      'Positiv: Bilanzeffekt (steigende Vermögenswerte fördern Investitionen)',
      'Negativ: Verlust der Informationsfunktion von Preisen',
      'Negativ: dauerhafte Senkung des Zinsniveaus ohne Risiken',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Positive Effekte sind Einkommens-/Vermögenseffekt, Bilanzeffekt und Übertragungseffekt (kurzfristig konsum- und investitionsfördernd). Negative Effekte sind Verlust der Informationsfunktion von Preisen, Kaufkraftverlust und Vertrauensverlust der Marktteilnehmer.',
  },

  // =====================================================================
  // Kapitel 9 · Kapitalanlage und Kapitalmarktanomalien
  // =====================================================================
  {
    id: 'bf-k9-q1',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Welche Informationsmenge umfasst die schwache Form der Informationseffizienz nach Fama?',
    options: [
      'Nur vergangene Informationen (historische Kursverläufe)',
      'Alle öffentlich zugänglichen Informationen',
      'Öffentliche und private (Insider-)Informationen',
      'Keine Informationen',
    ],
    correctAnswer: 0,
    explanation: 'Die schwache Form enthält nur vergangene Informationen (historische Kursverläufe sind eingepreist). Die halb-strenge Form umfasst alle öffentlich zugänglichen Informationen, die strenge Form zusätzlich private (Insider-)Informationen.',
  },
  {
    id: 'bf-k9-q2',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Was besagt das Grossman/Stiglitz-Informationsparadoxon (1980)?',
    options: [
      'Vollkommene Informationseffizienz ist logisch unmöglich, weil Informationsbeschaffung Kosten verursacht und einen Ertrag erbringen muss',
      'Märkte sind grundsätzlich vollständig informationseffizient',
      'Informationen sind stets kostenlos verfügbar',
      'Psychologie ist die alleinige Triebkraft der Kurse',
    ],
    correctAnswer: 0,
    explanation: 'Wäre der Markt vollkommen effizient, würde sich Informationsbeschaffung nicht lohnen; sucht aber niemand Informationen, lohnt sich die Suche wieder. Das Gleichgewicht liegt zwischen den Extremen – vollkommene Informationseffizienz ist logisch unmöglich.',
  },
  {
    id: 'bf-k9-q3',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'multiple',
    question: 'Welche Aussagen vertritt die Behavioral Finance (im Gegensatz zur Traditional Finance)?',
    options: [
      'Höhere Renditen lassen sich teils auch ohne höheres Risiko erzielen',
      'Wertpapierrenditen lassen sich zum Teil prognostizieren',
      'Märkte sind teilweise falsch bewertet',
      'Jeder Investor ist ein rationaler, nutzenoptimierender Homo Oeconomicus',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die Behavioral Finance vertritt: höhere Renditen auch ohne höheres Risiko, teilweise Prognostizierbarkeit der Renditen und teilweise falsch bewertete Märkte durch beschränkt rationale Investoren. Die Annahme des rationalen Homo Oeconomicus gehört zur Traditional Finance.',
  },
  {
    id: 'bf-k9-q4',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Was besagt der Winner-Loser-Effekt (De Bondt/Thaler 1985; Chopra/Lakonishok/Ritter 1992)?',
    options: [
      'Vergangene Gewinner bleiben dauerhaft Gewinner',
      'Vergangene Verlierer sind zukünftige Gewinner und umgekehrt (Mean Reversion infolge Überreaktion)',
      'Vergangene Verlierer bleiben dauerhaft Verlierer',
      'Es gibt keinen Zusammenhang zwischen vergangener und künftiger Performance',
    ],
    correctAnswer: 1,
    explanation: 'Der Winner-Loser-Effekt: Vergangene Verlierer sind zukünftige Gewinner, vergangene Gewinner zukünftige Verlierer (Mean Reversion infolge Überreaktion). Die risikoadjustierte Renditedifferenz beträgt 10,84 % und geht nicht mit höherem Beta einher.',
  },
  {
    id: 'bf-k9-q5',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Welche Aktien gelten nach dem Value-Effekt (Fama/French 1992) als zukünftige Gewinner?',
    options: [
      'Growth-Aktien mit niedriger Book-to-Market-Ratio',
      'Value-Aktien mit hoher Book-to-Market-Ratio',
      'Aktien mit dem höchsten CAPM-Beta',
      'Aktien mit niedrigster Dividende',
    ],
    correctAnswer: 1,
    explanation: 'Aktien mit hoher B/M-Ratio (Value, "günstige" Aktien) sind empirisch zukünftige Gewinner; Aktien mit niedriger B/M-Ratio (Growth, "teure" Aktien) zukünftige Verlierer. Die Renditedifferenz von 19,99 % ist sogar stärker als der Winner-Loser-Effekt.',
  },
  {
    id: 'bf-k9-q6',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Warum ist Fehlbewertung die wahrscheinlichste Erklärung für den Value-Effekt, und nicht das Risiko?',
    options: [
      'Weil ein hohes CAPM-Beta empirisch mit hohem Book-to-Market korreliert',
      'Weil ein hohes CAPM-Beta empirisch mit NIEDRIGEM Book-to-Market korreliert – das Gegenteil der Risiko-Hypothese – während Wachstumsraten mean reverting sind und Anleger Extreme zu weit fortschreiben',
      'Weil der Effekt nur in einer einzigen Stichprobe auftritt (Zufall)',
      'Weil Value-Aktien das höchste Risiko tragen',
    ],
    correctAnswer: 1,
    explanation: 'Die Risiko-Hypothese würde verlangen, dass hohes Beta mit hohem B/M einhergeht; empirisch korreliert hohes Beta jedoch mit niedrigem B/M (das Gegenteil). Zufall scheidet aus, weil internationale Stichproben vergleichbare Ergebnisse zeigen. Bleibt Fehlbewertung: Wachstumsraten sind mean reverting, Anleger extrapolieren Extreme zu weit.',
  },
  {
    id: 'bf-k9-q7',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Wie unterscheidet sich der Momentum-Effekt (Rouwenhorst 1998) vom Winner-Loser-Effekt?',
    options: [
      'Beim Momentum-Effekt werden vergangene Verlierer zu künftigen Gewinnern',
      'Beim Momentum-Effekt gilt kurzfristig: Winner bleiben Winner (Renditedifferenz 16,37 %)',
      'Der Momentum-Effekt tritt nur über Zeiträume von zehn Jahren auf',
      'Der Momentum-Effekt widerlegt jede Form von Trends',
    ],
    correctAnswer: 1,
    explanation: 'Anders als beim langfristigen Winner-Loser-Effekt (Mean Reversion) gilt beim kurzfristigen Momentum-Effekt: Winner bleiben Winner (kaufe die besten 6-Monats-Performer und halte 6 Monate). Die Renditedifferenz beträgt 16,37 %; der stabile Trendkern dauert typischerweise etwa ein Jahr.',
  },
  {
    id: 'bf-k9-q8',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Wie verhält sich ein typischer Anleger am Kapitalmarkt im Vergleich zum rationalen Verhalten im Supermarkt?',
    options: [
      'Antizyklisch: Er kauft bei fallenden Kursen (wie beim Steak-Rabatt)',
      'Prozyklisch: Er verkauft bei fallenden Kursen aus Angst und will bei steigenden Kursen kaufen – anders als beim rationalen antizyklischen Supermarkt-Verhalten',
      'Er handelt am Kapitalmarkt genauso antizyklisch wie im Supermarkt',
      'Er ignoriert Preisveränderungen vollständig',
    ],
    correctAnswer: 1,
    explanation: 'Im Supermarkt kauft man rational antizyklisch, wenn das Lieblings-Steak 30 % günstiger ist. Am Kapitalmarkt verhält sich der typische Anleger dagegen prozyklisch: Bei 30 % gefallenen Kursen verkauft er aus Angst, bei steigenden Kursen will er mehr kaufen.',
  },
];

export default questions;
