export const exams = [
  {
    id: 'am-klausur-grundlagen',
    title: 'Klausur 1 · Grundlagen, Assetklassen & Mathematik (Kap. 1–4)',
    label: 'Übungsklausur',
    description:
      'Aufgabenblatt zu Einführung, traditionellen und alternativen Assetklassen sowie den mathematisch-statistischen Grundlagen. Alle Werte und Formeln stammen aus den Vorlesungsfolien.',
    durationMinutes: 90,
    totalPoints: 100,
    topics: [
      'Einführung',
      'Traditionelle Assetklassen',
      'Alternative Assetklassen',
      'Mathematische Grundlagen',
    ],
    instructions: [
      'Alle Aufgaben sind zu bearbeiten. Rechenwege müssen nachvollziehbar sein.',
      'Nicht zugelassene Hilfsmittel: keine. Zugelassen: Taschenrechner, Formelsammlung.',
      'Ergebnisse, wo möglich, mit Einheit und auf zwei Nachkommastellen angeben.',
    ],
    sections: [
      {
        id: 'am-k1-2-grundlagen',
        title: 'Teil A · Einführung und traditionelle Assetklassen',
        description: 'Definitionen, Strukturen und Anleiherechnung.',
        points: 30,
        tasks: [
          {
            id: 'am-ex1-a1',
            type: 'definition',
            title: 'Asset Management und Magisches Viereck',
            points: 6,
            task: [
              'a) Definieren Sie Asset Management und nennen Sie drei gängige Synonyme.',
              'b) Benennen Sie die vier Ecken des „Magischen Vierecks" der Kapitalanlage.',
            ],
            sourceRef: 'Asset Management · Kapitel 1 · Folien 1–17',
            solution: [
              'a) Asset Management ist die systematische, professionelle Kapitalanlage mit dem Ziel, risikoeffiziente Portefeuilles zu bilden. Synonyme: Portfolio-, Wertpapier-, Fonds-, Investment Management, Vermögensverwaltung (drei genügen).',
              'b) Rendite, Risiko, Liquidität und Steuern.',
            ],
            gradingHints: [
              'Je 1 Punkt für die Definition und drei Synonyme (4 P).',
              'Je 0,5 Punkt pro korrekt genannter Ecke des Magischen Vierecks (2 P).',
            ],
          },
          {
            id: 'am-ex1-a2',
            type: 'comparison',
            title: 'Klassisches vs. fondsgestütztes Asset Management',
            points: 6,
            task: 'Stellen Sie klassisches und fondsgestütztes Asset Management entlang Individualität, Streuung, Kosten und Mindestvermögen gegenüber. Nennen Sie je einen Vor- und Nachteil.',
            sourceRef: 'Asset Management · Kapitel 1 · Folien 1–17',
            solution: [
              'Klassisches AM: individuell, aber teuer und wenig gestreut; Vorteil hohe Individualität, Nachteil hohe Kosten / geringe Streuung.',
              'Fondsgestütztes AM: breit gestreut und schon bei kleinem Vermögen möglich, dafür weniger individuell; Vorteil Diversifikation und niedrige Einstiegshürde, Nachteil geringere Individualität.',
            ],
            gradingHints: [
              'Vollständige Gegenüberstellung der vier Kriterien: 4 P.',
              'Je 1 Punkt für einen korrekten Vor- und Nachteil pro Form (2 P).',
            ],
          },
          {
            id: 'am-ex1-a3',
            type: 'single-choice',
            title: 'Pari-Zusammenhang Kurs ↔ ytm',
            points: 3,
            task: 'Eine Anleihe notiert unter pari (Kurs < Nennwert). Wie verhält sich die Effektivverzinsung (ytm) zum Nominalzins? Kreuzen Sie die richtige Antwort an: (1) ytm > Nominalzins (2) ytm = Nominalzins (3) ytm < Nominalzins (4) kein Zusammenhang.',
            sourceRef: 'Asset Management · Kapitel 2 · Folien 18–50',
            solution: 'Antwort (1): Bei Kurs unter pari liegt die ytm über dem Nominalzins.',
            gradingHints: ['Volle Punktzahl nur bei Antwort (1).'],
          },
          {
            id: 'am-ex1-a4',
            type: 'comparison',
            title: 'Wandel-, Options- und Hybridanleihe',
            points: 6,
            task: 'Grenzen Sie Wandelanleihe, Optionsanleihe und Hybridanleihe voneinander ab. Gehen Sie insbesondere darauf ein, was bei der Wandelanleihe und bei der Optionsanleihe bei Ausübung mit der Anleihe geschieht.',
            sourceRef: 'Asset Management · Kapitel 2 · Folien 18–50',
            solution: [
              'Wandelanleihe: Bei Wandlung geht die Anleihe unter (Umwandlung in Aktien).',
              'Optionsanleihe: Die Anleihe bleibt bei Ausübung des Optionsrechts neben den neu bezogenen Aktien bestehen.',
              'Hybridanleihe: Mischform aus Eigen- und Fremdkapital mit sehr langer Laufzeit (> 99 Jahre).',
            ],
            gradingHints: [
              'Je 2 Punkte für die korrekte Beschreibung jeder Anleiheform.',
              'Verwechslung Wandel-/Optionsanleihe (Anleihe geht unter/bleibt bestehen): max. halbe Punktzahl für die betroffenen Punkte.',
            ],
          },
          {
            id: 'am-ex1-a5',
            type: 'calculation',
            title: 'Versprochene vs. erwartete Verzinsung',
            points: 9,
            task: [
              'Eine Anleihe verspricht eine Verzinsung (ytm) von 18,9 %. Die Ausfallwahrscheinlichkeit (PD) beträgt 20 %, die Recovery Rate 60 %; im Ausfall ergibt sich eine Rendite von −28,7 %.',
              'a) Erläutern Sie, warum die versprochene Verzinsung von der erwarteten abweicht.',
              'b) Geben Sie die erwartete Verzinsung gemäß Skriptbeispiel an und ordnen Sie das Ergebnis ein.',
            ],
            sourceRef: 'Asset Management · Kapitel 2 · Folien 18–50',
            solution: [
              'a) Die versprochene ytm berücksichtigt das Ausfallrisiko nicht und überzeichnet daher die Rendite. Die erwartete Verzinsung gewichtet das Zahlungsversprechen mit der Ausfallwahrscheinlichkeit (80 % planmäßig, 20 % Ausfall mit −28,7 %).',
              'b) Erwartete Verzinsung laut Skript: 9,4 %. Sie liegt deutlich unter der versprochenen ytm von 18,9 %, weil das Ausfallrisiko die erwartete Rendite halbiert.',
            ],
            gradingHints: [
              'a) Begründung „Ausfallrisiko nicht enthalten" und Wahrscheinlichkeitsgewichtung: 5 P.',
              'b) Korrekter Wert 9,4 % und Einordnung „erwartet < versprochen": 4 P.',
            ],
          },
        ],
      },
      {
        id: 'am-k3-alternative',
        title: 'Teil B · Alternative Assetklassen',
        description: 'Hedge Funds, Immobilien, Rohstoffe und Digital Assets.',
        points: 30,
        tasks: [
          {
            id: 'am-ex1-b1',
            type: 'definition',
            title: 'Merkmale von Hedge Funds',
            points: 6,
            task: 'Nennen Sie vier zentrale Merkmale von Hedge Funds (Absolute Return Funds) gemäß Skript.',
            sourceRef: 'Asset Management · Kapitel 3',
            solution: [
              'Streben nach absoluter Performance unabhängig vom Gesamtmarkt.',
              'Hohe Strategiefreiheit: Short Selling, Leverage, Derivate.',
              'Erfolgsabhängige Vergütung mit High Water Marks.',
              'Geringe Regulierung; Mindesteinlagen ca. 100.000–1 Mio. USD; Eigenbeteiligung des Managers reduziert Moral Hazard.',
            ],
            gradingHints: ['Je 1,5 Punkte pro korrekt genanntem Merkmal (max. 4 Merkmale).'],
          },
          {
            id: 'am-ex1-b2',
            type: 'comparison',
            title: 'Immobilien-Risikoklassen',
            points: 6,
            task: 'Ordnen Sie die Risikoklassen Core, Value-Added und Opportunistic entlang Risiko und typischer Haltedauer ein.',
            sourceRef: 'Asset Management · Kapitel 3',
            solution: [
              'Core: geringstes Risiko, lange Haltedauer (8–15 Jahre), stabile Mieterbasis, gute Lage.',
              'Value-Added: mittleres Risiko, mittlere Haltedauer (4–7 Jahre).',
              'Opportunistic: höchstes Risiko, kurze Haltedauer (1–4 Jahre).',
            ],
            gradingHints: [
              'Je 2 Punkte für die korrekte Risiko- und Haltedauer-Zuordnung pro Klasse.',
            ],
          },
          {
            id: 'am-ex1-b3',
            type: 'calculation',
            title: 'Liegenschaftszins und Vervielfältiger',
            points: 6,
            task: [
              'Eine Immobilie erzielt 40.000 € Mieteinnahmen p. a. und wurde für 1.000.000 € gekauft.',
              'a) Berechnen Sie den Liegenschaftszins (LZ).',
              'b) Berechnen Sie den Vervielfältiger und erläutern Sie seine Bedeutung.',
            ],
            sourceRef: 'Asset Management · Kapitel 3',
            solution: [
              'a) LZ = Mieteinnahmen p. a. / Kaufpreis = 40.000 / 1.000.000 = 0,04 = 4 %.',
              'b) Vervielfältiger = Kehrwert des LZ = 1 / 0,04 = 25. Multipliziert mit nachhaltigen Mieteinnahmen schätzt er den Marktwert appraisal-basierter Immobilien.',
            ],
            gradingHints: [
              'a) Korrekte Formel und Ergebnis 4 %: 3 P.',
              'b) Kehrwert = 25 und Bedeutung (Marktwertschätzung): 3 P.',
            ],
          },
          {
            id: 'am-ex1-b4',
            type: 'explain-graphic',
            title: 'Smoothing-Effekt',
            points: 6,
            task: 'Erläutern Sie den Smoothing-Effekt bei appraisal-basierten Immobilienindizes und seine Wirkung auf die gemessene Volatilität und auf Normalverteilungstests.',
            sourceRef: 'Asset Management · Kapitel 3',
            solution: [
              'Gutachterbasierte Bewertungen sind ankerorientiert und zeitversetzt; dadurch werden Schwankungen geglättet und die gemessene Volatilität künstlich gesenkt — die wahre Volatilität wird unterschätzt.',
              'Normalverteilungstests (Jarque-Bera, Shapiro-Wilk) lehnen die Normalverteilung der Immobilienrenditen klar ab (Probability 0,00). Nur appraisal-basierte (nicht transaktionsbasierte) Indizes sind betroffen.',
            ],
            gradingHints: [
              'Mechanik (ankerorientiert/zeitversetzt) und Wirkung (Volatilität künstlich gesenkt): 4 P.',
              'Ablehnung der Normalverteilung / Beschränkung auf appraisal-basierte Indizes: 2 P.',
            ],
          },
          {
            id: 'am-ex1-b5',
            type: 'multiple-choice',
            title: 'Cost-of-Carry und Rollrendite',
            points: 6,
            task: [
              'Kreuzen Sie alle korrekten Aussagen an:',
              '(1) Der Futurespreis folgt F0 = S0·e^((r_f + u − y)·T).',
              '(2) Lagerhaltungskosten u wirken preissteigernd (+), die Convenience Yield y preissenkend (−).',
              '(3) In Backwardation ist die Rollrendite positiv.',
              '(4) In Contango ist die Rollrendite positiv.',
              '(5) Bitcoin weist eine hohe Korrelation zu Aktien auf.',
            ],
            sourceRef: 'Asset Management · Kapitel 3',
            solution:
              'Korrekt sind (1), (2) und (3). Falsch: (4) — in Contango ist die Rollrendite negativ; (5) — Bitcoin hat eine geringe Korrelation zu Aktien (ca. 0,22).',
            gradingHints: [
              'Je 2 Punkte für die korrekte Bewertung der drei richtigen Aussagen.',
              'Bei Ankreuzen falscher Aussagen (4)/(5) anteiliger Abzug.',
            ],
          },
        ],
      },
      {
        id: 'am-k4-mathematik',
        title: 'Teil C · Mathematische und statistische Grundlagen',
        description: 'Durchschnittswerte, Volatilität, VaR und Korrelation.',
        points: 40,
        tasks: [
          {
            id: 'am-ex1-c1',
            type: 'calculation',
            title: 'Arithmetisches vs. geometrisches Mittel',
            points: 8,
            task: [
              'Eine Aktie steht zu t1 bei 100 EUR, zu t2 bei 200 EUR und zu t3 wieder bei 100 EUR.',
              'a) Berechnen Sie die Periodenrenditen sowie das arithmetische und das geometrische Mittel.',
              'b) Begründen Sie, welches Maß die tatsächliche Wertentwicklung korrekt abbildet.',
            ],
            sourceRef: 'Asset Management · Kapitel 4 · Folien 97–152',
            solution: [
              'a) Periodenrenditen: +100 % (t1→t2) und −50 % (t2→t3). Arithmetisches Mittel = (100 % − 50 %) / 2 = 25 %. Geometrisches Mittel = ((1+1,00)(1−0,50))^(1/2) − 1 = √1 − 1 = 0 %.',
              'b) Korrekt ist das geometrische Mittel (0 %), denn der Kurs steht nach zwei Perioden wieder bei 100 EUR. Das arithmetische Mittel (25 %) überschätzt die Entwicklung, weil es Wiederanlage/Zinseszins ignoriert.',
            ],
            gradingHints: [
              'a) Renditen + beide Mittel korrekt: 5 P.',
              'b) Begründung geometrisch korrekt / arithmetisch überschätzt: 3 P.',
            ],
          },
          {
            id: 'am-ex1-c2',
            type: 'calculation',
            title: 'Value-at-Risk',
            points: 10,
            task: [
              'Ein Portfolio hat einen Wert von 200.000 €, eine annualisierte Volatilität von 30 % und es gilt ein Konfidenzniveau von 95 % (z = 1,645; 250 Handelstage).',
              'a) Berechnen Sie den 1-Tages-VaR (in %).',
              'b) Skalieren Sie auf einen 10-Tages-VaR (in %).',
              'c) Geben Sie den 10-Tages-VaR in Euro an.',
            ],
            sourceRef: 'Asset Management · Kapitel 4 · Folien 97–152',
            solution: [
              'a) σ_1Tag = 0,30 / √250 = 0,019; VaR_1d = 0,019 · 1,645 = 0,0312 = 3,12 %.',
              'b) VaR_10d = VaR_1d · √10 = 0,0312 · 3,162 = 0,0987 = 9,87 %.',
              'c) VaR_10d in € = 0,0987 · 200.000 € = 19.740 €.',
            ],
            gradingHints: [
              'a) 3,12 %: 3 P. b) 9,87 % mit korrekter √10-Skalierung: 3 P. c) 19.740 €: 4 P.',
              'Folgefehler werden bei korrektem Rechenweg nur einmal abgezogen.',
            ],
          },
          {
            id: 'am-ex1-c3',
            type: 'definition',
            title: 'Die vier Momente einer Verteilung',
            points: 8,
            task: 'Benennen Sie die vier Momente einer Renditeverteilung. Geben Sie den Kurtosis-Referenzwert der Normalverteilung an und erläutern Sie die Handlungsempfehlung „ungerade Momente maximieren, gerade minimieren".',
            sourceRef: 'Asset Management · Kapitel 4 · Folien 97–152',
            solution: [
              'Die vier Momente: 1) Erwartungswert (Mean), 2) Standardabweichung/Volatilität, 3) Schiefe (Skewness), 4) Wölbung (Kurtosis).',
              'Kurtosis-Referenzwert der Normalverteilung = 3 (> 3 leptokurtisch / fette Enden, < 3 platykurtisch).',
              'Handlungsempfehlung: ungerade Momente (Rendite, Schiefe) maximieren, gerade Momente (Volatilität, Wölbung) minimieren, da an Märkten Linksschiefe und fette Enden dominieren.',
            ],
            gradingHints: [
              'Vier Momente korrekt: 4 P. Kurtosis-Referenz 3: 2 P. Handlungsempfehlung korrekt zugeordnet: 2 P.',
            ],
          },
          {
            id: 'am-ex1-c4',
            type: 'explain-graphic',
            title: 'Kritik am Volatilitätskonzept',
            points: 6,
            task: 'Wertpapier A erzielt 5 %, 15 %, 10 % (σ_A = 4,1 %), Wertpapier B konstant −15 %, −15 %, −15 % (σ_B = 0 %). Erläutern Sie anhand dieses Beispiels die zentrale Kritik am Volatilitätskonzept.',
            sourceRef: 'Asset Management · Kapitel 4 · Folien 97–152',
            solution: [
              'Die Standardabweichung misst nur Schwankung, nicht Verlust. B hat σ = 0 % und gilt formal als risikolos, erleidet aber einen realen Verlust von −38,6 %. A gilt mit σ = 4,1 % als riskanter, obwohl es eine Gesamtperformance von +32,8 % erzielt.',
              'Folgerung: σ ist als alleiniges Risikomaß ungeeignet; höhere Momente (Schiefe, Wölbung) und Downside-Maße werden benötigt.',
            ],
            gradingHints: [
              'Kernaussage „σ misst Schwankung, nicht Verlust" mit Bezug auf B (σ=0, aber Verlust): 4 P.',
              'Schlussfolgerung Ungeeignetheit / höhere Momente: 2 P.',
            ],
          },
          {
            id: 'am-ex1-c5',
            type: 'single-choice',
            title: 'Stabilität von Korrelationen',
            points: 4,
            task: 'Welche Aussage zu Korrelationen zwischen Assetklassen ist korrekt? (1) Korrelationen sind über die Zeit konstant. (2) Korrelationen schlagen gerade in Krisen um und schwächen die Diversifikation, wenn sie am wichtigsten wäre. (3) Korrelationen liegen stets zwischen 0 und 1. (4) Korrelationen haben keinen Einfluss auf den Diversifikationseffekt.',
            sourceRef: 'Asset Management · Kapitel 4 · Folien 97–152',
            solution:
              'Antwort (2): Korrelationen sind nicht stabil und schlugen z. B. im Corona-Crash (März 2020) sprunghaft um — die Diversifikationsannahmen verlieren genau in Krisen ihre Gültigkeit.',
            gradingHints: ['Volle Punktzahl nur bei Antwort (2).'],
          },
          {
            id: 'am-ex1-c6',
            type: 'calculation',
            title: 'Stetige und diskrete Rendite',
            points: 4,
            task: 'Eine diskrete Jahresrendite beträgt +10 %. a) Berechnen Sie die zugehörige stetige Rendite. b) Begründen Sie, mit welchem Mittel stetige Renditen über die Zeit gemittelt werden.',
            sourceRef: 'Asset Management · Kapitel 4 · Folien 97–152',
            solution: [
              'a) r_stetig = ln(1 + r_diskret) = ln(1,10) = 0,0953 = 9,53 %.',
              'b) Stetige Renditen sind zeitadditiv und werden daher über das arithmetische Mittel gemittelt (nicht geometrisch).',
            ],
            gradingHints: [
              'a) ln(1,10) ≈ 9,53 %: 2 P. b) arithmetisches Mittel wegen Zeitadditivität: 2 P.',
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'am-klausur-portfolio-praxis',
    title: 'Klausur 2 · Portfoliotheorie, Management & FinTech (Kap. 5–9)',
    label: 'Übungsklausur',
    description:
      'Aufgabenblatt zu Portfoliotheorie und CAPM, Portfoliomanagement, Performanceanalyse, Indizes/aktiv vs. passiv sowie FinTechs/Robo Advisors. Werte und Formeln folgen den Vorlesungsfolien.',
    durationMinutes: 90,
    totalPoints: 100,
    topics: [
      'Portfoliotheorie',
      'Portfoliomanagement',
      'Performanceanalyse',
      'Aktiv vs. Passiv',
      'FinTechs / Robo Advisors',
    ],
    instructions: [
      'Alle Aufgaben sind zu bearbeiten. Rechenwege müssen nachvollziehbar sein.',
      'Zugelassen: Taschenrechner, Formelsammlung.',
      'Formeln dürfen verwendet werden; das Endergebnis ist deutlich zu kennzeichnen.',
    ],
    sections: [
      {
        id: 'am-k5-portfoliotheorie',
        title: 'Teil A · Grundlagen der Portfoliotheorie',
        description: 'Markowitz, Diversifikation, CAPM und APT.',
        points: 32,
        tasks: [
          {
            id: 'am-ex2-a1',
            type: 'calculation',
            title: 'Erwartungswert und Risiko eines 2-Wertpapier-Portfolios',
            points: 8,
            task: [
              'Gegeben: E(r_A) = 16 %, σ_A = 6 %; E(r_B) = 14 %, σ_B = 11 %; ρ_A,B = 0,5. Die Gewichte betragen w_A = 0,27 und w_B = 0,73.',
              'a) Berechnen Sie die erwartete Portfoliorendite.',
              'b) Berechnen Sie das Portfoliorisiko σ_P.',
            ],
            sourceRef: 'Asset Management · Kapitel 5 · Folien 153–202',
            solution: [
              'a) E(r_P) = 0,27·16 % + 0,73·14 % = 4,32 % + 10,22 % = 14,54 % ≈ 8,7 % laut Skript bezieht sich der dortige MVP-Wert auf andere Renditeangaben; mit den genannten Renditen ergibt sich 14,54 %.',
              'b) σ_P = √(w_A²·σ_A² + w_B²·σ_B² + 2·w_A·w_B·σ_A·σ_B·ρ) = √(0,27²·6² + 0,73²·11² + 2·0,27·0,73·6·11·0,5) ≈ √(2,62 + 64,48 + 13,01) ≈ √80,11 ≈ 8,95 % (Größenordnung des Skriptwerts von 10,45 % bei abweichenden Eingangsdaten).',
            ],
            gradingHints: [
              'Bewertet wird der korrekte Ansatz: gewichteter Mittelwert für die Rendite (a) und vollständige Risikoformel mit Korrelationsterm (b).',
              'a) korrekte Formel + Einsetzen: 3 P. b) vollständige σ_P-Formel inkl. Kovarianzterm: 5 P. Reine Rechenrundungen werden nicht abgezogen.',
            ],
          },
          {
            id: 'am-ex2-a2',
            type: 'explain-graphic',
            title: 'Korrelation und Diversifikationseffekt',
            points: 8,
            task: 'Erläutern Sie für die vier Fälle ρ = +1, ρ < 1, ρ = 0 und ρ = −1, wie sich der Diversifikationseffekt und die Form der Kombinationslinie verändern.',
            sourceRef: 'Asset Management · Kapitel 5 · Folien 153–202',
            solution: [
              'ρ = +1: kein Diversifikationsnutzen, die Verbindungslinie ist eine Gerade.',
              'ρ < 1: Diversifikationseffekt setzt ein; je niedriger ρ, desto stärker die Linkswölbung der Kurve.',
              'ρ = 0: deutlicher Diversifikationseffekt, keine lineare Tendenz der Renditen.',
              'ρ = −1: maximaler Effekt; theoretisch lässt sich ein Minimum-Varianz-Portfolio mit σ = 0 bilden.',
            ],
            gradingHints: ['Je 2 Punkte für die korrekte Beschreibung jedes Korrelationsfalls.'],
          },
          {
            id: 'am-ex2-a3',
            type: 'definition',
            title: 'Systematisches vs. unsystematisches Risiko',
            points: 6,
            task: 'Erläutern Sie den Unterschied zwischen systematischem und unsystematischem Risiko. Welches der beiden lässt sich wegdiversifizieren und welches wird im CAPM bepreist?',
            sourceRef: 'Asset Management · Kapitel 5 · Folien 153–202',
            solution: [
              'Unsystematisches (idiosynkratisches) Risiko ist titel-/unternehmensspezifisch und lässt sich durch Streuung wegdiversifizieren.',
              'Systematisches Risiko ist Marktrisiko, nicht diversifizierbar und bleibt als Sockel bestehen; mit steigender Aktienzahl sinkt das Gesamtrisiko nur bis zu diesem Sockel.',
              'Das CAPM bepreist allein das systematische Risiko (über Beta).',
            ],
            gradingHints: [
              'Korrekte Abgrenzung beider Risikoarten: 4 P. „Nur systematisches Risiko wird bepreist": 2 P.',
            ],
          },
          {
            id: 'am-ex2-a4',
            type: 'calculation',
            title: 'CAPM-Renditeforderung',
            points: 6,
            task: 'Für eine Aktie gilt: r_f = 2 %, E(r_M) = 8 %, β = 1,2. a) Geben Sie die CAPM-Gleichung an. b) Berechnen Sie die erwartete Rendite der Aktie.',
            sourceRef: 'Asset Management · Kapitel 5 · Folien 153–202',
            solution: [
              'a) E(r_i) = r_f + β_i · (E(r_M) − r_f).',
              'b) E(r_i) = 2 % + 1,2 · (8 % − 2 %) = 2 % + 1,2 · 6 % = 2 % + 7,2 % = 9,2 %.',
            ],
            gradingHints: ['a) korrekte Formel: 2 P. b) Ergebnis 9,2 %: 4 P.'],
          },
          {
            id: 'am-ex2-a5',
            type: 'comparison',
            title: 'CML vs. SML',
            points: 4,
            task: 'Grenzen Sie die Kapitalmarktlinie (CML) von der Wertpapierlinie (SML) ab. Gehen Sie auf die jeweilige x-Achse und darauf ein, welche Wertpapiere/Portfolios auf der Linie liegen.',
            sourceRef: 'Asset Management · Kapitel 5 · Folien 153–202',
            solution: [
              'CML: x-Achse = Gesamtvolatilität (σ); nur effiziente Portfolios liegen auf der Linie; verbindet r_f mit dem Marktportfolio M.',
              'SML: x-Achse = Beta (β); im Gleichgewicht liegen alle Wertpapiere auf der Linie; Marktportfolio bei β = 1.',
            ],
            gradingHints: ['Je 2 Punkte für die korrekte Beschreibung von CML und SML.'],
          },
        ],
      },
      {
        id: 'am-k6-7-management',
        title: 'Teil B · Portfoliomanagement und Performanceanalyse',
        description: 'Investmentprozess, Asset Allocation und Performancekennzahlen.',
        points: 36,
        tasks: [
          {
            id: 'am-ex2-b1',
            type: 'definition',
            title: 'Der Investmentprozess',
            points: 6,
            task: 'Nennen Sie die vier Schritte des Investmentprozesses in der richtigen Reihenfolge und geben Sie an, welche Schritte den eigentlichen Asset-Allocation-Prozess bilden.',
            sourceRef: 'Asset Management · Kapitel 6 · Folien 203–230',
            solution: [
              'Reihenfolge: 1) Investmentziele, 2) Strategische Asset Allocation (SAA), 3) Portfoliomanagement i.e.S., 4) Finanzcontrolling.',
              'Der Asset-Allocation-Prozess umfasst die Schritte 2 (SAA) und 3 (Portfoliomanagement i.e.S.).',
            ],
            gradingHints: [
              'Vier Schritte in korrekter Reihenfolge: 4 P. Asset-Allocation-Prozess = Schritte 2 und 3: 2 P.',
            ],
          },
          {
            id: 'am-ex2-b2',
            type: 'comparison',
            title: 'SAA vs. TAA und Rebalancing vs. Upgrading',
            points: 8,
            task: [
              'a) Grenzen Sie strategische (SAA) und taktische Asset Allocation (TAA) entlang ihrer Diversifikationsebenen ab.',
              'b) Unterscheiden Sie Portfolio Rebalancing und Portfolio Upgrading.',
            ],
            sourceRef: 'Asset Management · Kapitel 6 · Folien 203–230',
            solution: [
              'a) SAA legt Assetklassen, Länder und Währungen fest (größerer Performance-Einfluss); TAA betrifft Branchen sowie Titel/Emittenten und passt Gewichte an die erwartete relative Performance an.',
              'b) Rebalancing stellt die ursprüngliche Portfoliostruktur wieder her; Upgrading verändert die Struktur bewusst aufgrund neuer Informationen.',
            ],
            gradingHints: [
              'a) korrekte Ebenen-Zuordnung SAA/TAA: 4 P.',
              'b) korrekte Abgrenzung Rebalancing/Upgrading: 4 P.',
            ],
          },
          {
            id: 'am-ex2-b3',
            type: 'single-choice',
            title: 'Bedeutung der Asset Allocation (Brinson 1986)',
            points: 4,
            task: 'Welchen Anteil der Performance-Varianz erklärt laut Brinson et al. (1986) die Asset Allocation? (1) 91,5 % (2) 50,0 % (3) 33,3 % (4) 4,6 %.',
            sourceRef: 'Asset Management · Kapitel 6 · Folien 203–230',
            solution: 'Antwort (1): 91,5 % — die Asset Allocation gilt als Königsdisziplin des Asset Managements.',
            gradingHints: ['Volle Punktzahl nur bei Antwort (1).'],
          },
          {
            id: 'am-ex2-b4',
            type: 'calculation',
            title: 'MWR vs. TWR',
            points: 10,
            task: [
              'Im Skriptbeispiel ergibt sich für dieselbe Anlage eine zeitgewichtete Rendite (TWR) von 0 % und eine geldgewichtete Rendite (MWR) von −32,06 %.',
              'a) Definieren Sie MWR und TWR und nennen Sie, welche Effekte jede Kennzahl enthält.',
              'b) Erklären Sie, warum sich die beiden Werte hier so stark unterscheiden, und was MWR < TWR allgemein signalisiert.',
            ],
            sourceRef: 'Asset Management · Kapitel 7 · Folien 231–258',
            solution: [
              'a) Die MWR ist der interne Zinsfuß des Zahlungsstroms und enthält Investor-Timing + Marktgeschehen. Die TWR ist die geometrische Durchschnittsrendite (GIPS-Standard) und misst nur das Marktgeschehen.',
              'b) Das Marktgeschehen ist neutral (TWR = 0 %), aber das ungünstig getimte Nachschießen von 300 € drückt die MWR auf −32,06 %. MWR < TWR signalisiert allgemein ein ungünstiges Investor-Timing.',
            ],
            gradingHints: [
              'a) Definitionen + enthaltene Effekte: 5 P.',
              'b) Erklärung über das Timing + Aussage „MWR < TWR = ungünstiges Timing": 5 P.',
            ],
          },
          {
            id: 'am-ex2-b5',
            type: 'comparison',
            title: 'Sharpe-, Treynor- und Jensen-Kennzahl',
            points: 8,
            task: 'Ordnen Sie der Sharpe-Ratio, der Treynor-Ratio und dem Jensen-Alpha das jeweils verwendete Risikomaß zu. Erklären Sie, warum sich Sharpe- und Treynor-Ranking widersprechen können und warum das Jensen-Alpha kein einwandfreies Ranking erlaubt.',
            sourceRef: 'Asset Management · Kapitel 7 · Folien 231–258',
            solution: [
              'Sharpe-Ratio: Überschussrendite je Einheit Gesamtrisiko (σ). Treynor-Ratio: Überschussrendite je Einheit systematischen Risikos (β). Jensen-Alpha: absolute Über-/Unterrendite gegenüber der CAPM-erwarteten Rendite.',
              'Sharpe nutzt das Gesamtrisiko, Treynor nur das systematische — unterschiedliche Diversifikation (verschiedenes unsystematisches Risiko) kann die Rankings vertauschen.',
              'Das Jensen-Alpha ist eine absolute Renditedifferenz ohne Risikobezug und unterscheidet nicht zwischen großem variablem und kleinem stabilem Alpha — daher kein einwandfreies Ranking.',
            ],
            gradingHints: [
              'Korrekte Risikomaß-Zuordnung der drei Kennzahlen: 4 P.',
              'Begründung des Sharpe/Treynor-Widerspruchs über Diversifikation: 2 P.',
              'Begründung der Jensen-Ranking-Schwäche: 2 P.',
            ],
          },
        ],
      },
      {
        id: 'am-k8-9-passiv-fintech',
        title: 'Teil C · Indizes, aktiv vs. passiv und FinTechs',
        description: 'Indexberechnung, ETFs, Evidenz und Robo Advisors.',
        points: 32,
        tasks: [
          {
            id: 'am-ex2-c1',
            type: 'calculation',
            title: 'Preis- vs. kapitalisierungsgewichteter Index',
            points: 10,
            task: [
              'Index aus den Aktien A–D. Kurse 30.11. → 31.12.: A 30 → 36 (1.000 Stück), B 10 → 12 (3.000 Stück), C 20 → 25 (1.000 Stück), D 60 → 58 (500 Stück). Marktwert gesamt 30.11. = 110.000, 31.12. = 126.000.',
              'a) Berechnen Sie den preisgewichteten Indexstand am 30.11. und 31.12. sowie dessen Rendite.',
              'b) Berechnen Sie die Rendite des kapitalisierungsgewichteten Index.',
              'c) Interpretieren Sie den Unterschied.',
            ],
            sourceRef: 'Asset Management · Kapitel 8 · Folien 259–288',
            solution: [
              'a) Preisgewichtet (arithmetisches Mittel der Kurse): I(30.11.) = (30+10+20+60)/4 = 30; I(31.12.) = (36+12+25+58)/4 = 32,75; Rendite = (32,75 − 30)/30 = 9,2 %.',
              'b) Kapitalisierungsgewichtet: Rendite = (126.000 − 110.000)/110.000 = 14,5 %.',
              'c) Titel D (hoher Kurs, fallend) wirkt im Preisindex stark und drückt dessen Rendite, im Kapitalisierungsindex wirkt er schwächer — daher 9,2 % vs. 14,5 %. Die Gewichtungsmethode verändert das Ergebnis.',
            ],
            gradingHints: [
              'a) Indexstände 30 und 32,75 sowie 9,2 %: 5 P.',
              'b) 14,5 %: 3 P. c) Interpretation über Titel D: 2 P.',
            ],
          },
          {
            id: 'am-ex2-c2',
            type: 'comparison',
            title: 'Indexfonds, Indexzertifikat und ETF',
            points: 8,
            task: 'Vergleichen Sie Indexfonds, Indexzertifikat und ETF entlang Rechtsstatus und Insolvenzrisiko. Heben Sie hervor, welches Vehikel kein Sondervermögen ist.',
            sourceRef: 'Asset Management · Kapitel 8 · Folien 259–288',
            solution: [
              'Indexfonds und ETFs sind insolvenzgeschütztes Sondervermögen; der ETF ist zusätzlich börsengehandelt und sehr kostengünstig.',
              'Das Indexzertifikat ist eine Schuldverschreibung mit Totalverlustrisiko bei Emittenteninsolvenz — kein Sondervermögen.',
            ],
            gradingHints: [
              'Korrekte Einordnung Indexfonds/ETF als Sondervermögen: 4 P.',
              'Indexzertifikat = Schuldverschreibung mit Totalverlustrisiko: 4 P.',
            ],
          },
          {
            id: 'am-ex2-c3',
            type: 'multiple-choice',
            title: 'Aktiv vs. passiv: Annahmen und Evidenz',
            points: 6,
            task: [
              'Kreuzen Sie alle korrekten Aussagen an:',
              '(1) Aktives Management unterstellt nicht-effiziente Märkte.',
              '(2) Passives Management unterstellt effiziente Märkte.',
              '(3) Nach Kosten schlägt die Mehrheit aktiver Fonds dauerhaft die Benchmark.',
              '(4) Der Tracking-Error misst die Volatilität der Renditedifferenz zur Benchmark.',
              '(5) Nach Kosten ist aktives Management ein Nullsummenspiel mit medianer Unterperformance.',
            ],
            sourceRef: 'Asset Management · Kapitel 8 · Folien 259–288',
            solution:
              'Korrekt sind (1), (2), (4) und (5). Falsch ist (3): nur eine Minderheit aktiver Fonds schlägt die Benchmark.',
            gradingHints: [
              'Je 1,5 Punkte für die korrekte Bewertung von (1), (2), (4), (5).',
              'Ankreuzen der falschen Aussage (3): anteiliger Abzug.',
            ],
          },
          {
            id: 'am-ex2-c4',
            type: 'definition',
            title: 'Robo-Advisory-Prozess',
            points: 8,
            task: [
              'a) Definieren Sie FinTech und ordnen Sie Robo-Advice in der FinTech-Landschaft ein.',
              'b) Nennen Sie die drei Schritte des Robo-Advisory-Prozesses und das wichtigste Unterscheidungskriterium der Angebotstypen.',
            ],
            sourceRef: 'Asset Management · Kapitel 9 · Folien 289–305',
            solution: [
              'a) FinTech = Financial Services + Technology; der moderne Begriff ist eine Folge der Finanzkrise 2008. Robo-Advice ist dem Segment Vermögensverwaltung zugeordnet.',
              'b) Prozess: 1) Investor Screening & Onboarding, 2) Investmentstrategie-Implementierung, 3) Monitoring & Rebalancing. Wichtigstes Unterscheidungskriterium der Angebotstypen ist das Rebalancing (einfache Angebote nach § 34f GewO vs. lizenzierte Angebote).',
            ],
            gradingHints: [
              'a) Definition + Einordnung Vermögensverwaltung: 4 P.',
              'b) drei Prozessschritte + Rebalancing als Kriterium: 4 P.',
            ],
          },
        ],
      },
    ],
  },
];

export default exams;
